### ISSUE TITLE
problema na conversão

### ISSUE THREAD

**Issue by helder-rangel** [phfaustini/Springer_csv2bib#1]
Tentei usar aplicativo no Ubuntu, com python 3.9, mas a seguinte mensagem de erro foi gerada:

bitnami@ip-172-31-56-236:~/scopus$ python3 springer_csv2bib.py scopus.csv
Traceback (most recent call last):
  File "/home/bitnami/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Book Series Title'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "springer_csv2bib.py", line 87, in <module>
    convert_csv2bib(filepath=argv[1])
  File "springer_csv2bib.py", line 74, in convert_csv2bib
    bibentries = _get_bibentries(filepath)
  File "springer_csv2bib.py", line 46, in _get_bibentries
    bibentry.Book_Series_Title = row['Book Series Title']
  File "/home/bitnami/.local/lib/python3.7/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/home/bitnami/.local/lib/python3.7/site-packages/pandas/core/series.py", line 989, in _get_value
    loc = self.index.get_loc(label)
  File "/home/bitnami/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'Book Series Title'

**Comment by phfaustini** [comment]
Provavelmente eu esteja respondendo isso tarde mais, mas mesmo assim: independente de usar Python 3.9, é necessário que o arquivo .csv seja extraído do site da Springer, pois assim ele terá os headers corretos. Coloquei um arquivo .csv de exemplo.
